import { useEffect, useMemo, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from '../components/ui'
import { useAuth } from '../context/AuthContext'
import { loadSurveyRecords } from '../lib/records'
import { listSurveys } from '../lib/surveys'
import { getSupabase } from '../lib/supabase'
import type { RecordAnswer, RecordQuestion, RecordSubmission, SurveyListItem, SurveyRecordData, SurveyRoundSummary, SurveyStatus, SurveyType } from '../types/survey'

const statusLabels:Record<SurveyStatus,string>={draft:'초안',scheduled:'예정',open:'진행 중',closed:'종료',archived:'보관'}
const roundLabels={single:'단회',pre:'사전',post:'사후'} as const
const date=(value:string|null,withTime=false)=>value?new Date(value).toLocaleString('ko-KR',withTime?undefined:{year:'numeric',month:'numeric',day:'numeric'}):'—'
const percent=(n:number,total:number)=>total?Math.round(n/total*100):0
const photoUrl=(path:string|null)=>path?(path.startsWith('http')?path:getSupabase()?.storage.from('client-photos').getPublicUrl(path).data.publicUrl??''):''

export function RecordsPage(){
  const {surveyId}=useParams();return surveyId?<RecordDetail surveyId={surveyId}/>:<RecordFinder/>
}

function RecordFinder(){
  const {profile}=useAuth();const [items,setItems]=useState<SurveyListItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [search,setSearch]=useState('');const [type,setType]=useState<'all'|SurveyType>('all');const [status,setStatus]=useState<'all'|'open'|'closed'|'archived'>('all');const [from,setFrom]=useState('');const [to,setTo]=useState('')
  useEffect(()=>{if(!profile)return;setLoading(true);listSurveys(profile.organization_id).then(setItems).catch(e=>setError(e instanceof Error?e.message:'기록을 불러오지 못했습니다.')).finally(()=>setLoading(false))},[profile])
  const shown=useMemo(()=>items.filter(i=>['open','closed','archived'].includes(i.status)&&(type==='all'||i.survey_type===type)&&(status==='all'||i.status===status)&&`${i.title} ${i.program_name??''}`.toLowerCase().includes(search.toLowerCase())&&(!from||Boolean(i.starts_at&&i.starts_at.slice(0,10)>=from))&&(!to||Boolean((i.ends_at??i.starts_at)&&((i.ends_at??i.starts_at)!.slice(0,10)<=to)))),[items,type,status,search,from,to])
  return <><PageHeader title="기록·결과" description="조사를 찾아 완료 현황, 실제 응답, 결과 분석과 보고서를 한 흐름에서 확인합니다."/>{error&&<ErrorState message={error}/>}<section className="completion-filters panel"><label>조사 또는 프로그램<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="조사 제목, 프로그램 검색"/></label><label>조사 유형<select value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="all">단회 / 사전·사후</option><option value="single">단회</option><option value="pre_post">사전·사후</option></select></label><label>상태<select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">진행 중 / 종료 / 보관</option><option value="open">진행 중</option><option value="closed">종료</option><option value="archived">보관</option></select></label><label>시작 기간<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>종료 기간<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></section>{loading?<LoadingState/>:shown.length?<div className="survey-grid">{shown.map(item=>{const rounds=item.rounds.filter(r=>r.status!=='pending');const completed=rounds.reduce((sum,r)=>sum+r.completed_count,0);const denominator=item.participant_count*Math.max(1,rounds.length);return <article className="survey-card" key={item.id}><div className="badge-stack"><StatusBadge>{item.survey_type==='single'?'단회':'사전·사후'}</StatusBadge><StatusBadge tone={item.status==='open'?'success':'neutral'}>{statusLabels[item.status]}</StatusBadge></div><h2>{item.title}</h2><p>{item.program_name??'프로그램 미지정'}</p><dl className="round-metrics"><div><dt>회차 상태</dt><dd>{rounds.map(r=>`${roundLabels[r.round_type]} ${r.status==='open'?'진행':'종료'}`).join(' · ')||'—'}</dd></div><div><dt>참여 인원</dt><dd>{item.participant_count}명</dd></div><div><dt>완료</dt><dd>{completed}건</dd></div><div><dt>완료율</dt><dd>{percent(completed,denominator)}%</dd></div></dl><p>시작 {date(item.starts_at)} · 종료 {date(item.ends_at)}</p><Link className="button primary" to={`/records/${item.id}`}>기록·결과 보기</Link></article>})}</div>:<EmptyState title="조건에 맞는 조사가 없습니다." description="검색어나 기간 필터를 변경해 주세요."/>}</>
}

type Tab='completion'|'analysis'|'responses'|'report'
function RecordDetail({surveyId}:{surveyId:string}){
  const {profile}=useAuth();const [params,setParams]=useSearchParams();const tab=(['completion','analysis','responses','report'].includes(params.get('tab')??'')?params.get('tab'):'completion') as Tab;const [data,setData]=useState<SurveyRecordData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
  useEffect(()=>{if(!profile)return;setLoading(true);loadSurveyRecords(surveyId,profile.organization_id).then(setData).catch(e=>setError(e instanceof Error?e.message:'기록을 불러오지 못했습니다.')).finally(()=>setLoading(false))},[profile,surveyId])
  if(loading)return <LoadingState/>;if(error||!data)return <><PageHeader title="기록·결과"/><ErrorState message={error||'조사를 찾을 수 없습니다.'}/><Link className="button secondary" to="/records">조사 찾기로</Link></>
  const submitted=data.submissions.filter(s=>s.status==='submitted');const completedClients=new Set(submitted.map(s=>s.client_id));const pre=data.rounds.find(r=>r.round_type==='pre');const post=data.rounds.find(r=>r.round_type==='post');const preIds=new Set(submitted.filter(s=>s.survey_round_id===pre?.id).map(s=>s.client_id));const postIds=new Set(submitted.filter(s=>s.survey_round_id===post?.id).map(s=>s.client_id));const paired=[...preIds].filter(id=>postIds.has(id)).length
  const setTab=(next:Tab)=>{const nextParams=new URLSearchParams(params);nextParams.set('tab',next);setParams(nextParams)}
  return <><PageHeader title={data.project.title} description={`${data.project.program_name??'프로그램 미지정'} · 기록·결과`} action={<Link className="button secondary" to="/records">다른 조사 찾기</Link>}/><section className="panel project-summary"><div className="badge-stack"><StatusBadge>{data.project.survey_type==='single'?'단회':'사전·사후'}</StatusBadge><StatusBadge tone={data.project.status==='open'?'success':'neutral'}>{statusLabels[data.project.status]}</StatusBadge></div><dl className="round-metrics"><div><dt>참여자</dt><dd>{data.participants.length}명</dd></div><div><dt>완료 이용인</dt><dd>{completedClients.size}명</dd></div><div><dt>미완료</dt><dd>{Math.max(0,data.participants.length-completedClients.size)}명</dd></div><div><dt>완료율</dt><dd>{percent(completedClients.size,data.participants.length)}%</dd></div><div><dt>시작일</dt><dd>{date(data.project.starts_at)}</dd></div><div><dt>종료일</dt><dd>{date(data.project.ends_at)}</dd></div>{data.project.survey_type==='pre_post'&&<><div><dt>사전 완료</dt><dd>{preIds.size}명</dd></div><div><dt>사후 완료</dt><dd>{postIds.size}명</dd></div><div><dt>모두 완료</dt><dd>{paired}명</dd></div></>}</dl></section><div className="record-tabs" role="tablist">{([['completion','완료 현황'],['analysis','결과 분석'],['responses','응답 기록'],['report','보고서']] as const).map(([value,label])=><button role="tab" aria-selected={tab===value} className={tab===value?'active':''} onClick={()=>setTab(value)} key={value}>{label}</button>)}</div>{tab==='completion'&&<CompletionTab data={data}/>} {tab==='responses'&&<ResponsesTab data={data}/>} {tab==='analysis'&&<AnalysisTab data={data} initialRoundId={params.get('roundId')}/>} {tab==='report'&&<ReportTab data={data}/>}</>
}

function CompletionTab({data}:{data:SurveyRecordData}){return <div className="completion-list">{data.rounds.filter(r=>r.status!=='pending').map(round=><RoundCompletion key={round.id} data={data} round={round}/>)}</div>}
function RoundCompletion({data,round}:{data:SurveyRecordData;round:SurveyRoundSummary}){const states=new Map(data.submissions.filter(s=>s.survey_round_id===round.id).map(s=>[s.client_id,s]));const completed=[...states.values()].filter(s=>s.status==='submitted').length;return <article className="completion-card panel"><header><div><StatusBadge tone={round.status==='open'?'success':'neutral'}>{roundLabels[round.round_type]} · {round.status==='open'?'진행 중':'종료'}</StatusBadge><h2>{data.project.title}</h2></div><strong className="completion-rate">{percent(completed,data.participants.length)}%</strong></header><dl className="round-metrics"><div><dt>전체</dt><dd>{data.participants.length}명</dd></div><div><dt>완료</dt><dd>{completed}명</dd></div><div><dt>미완료</dt><dd>{data.participants.length-completed}명</dd></div><div><dt>시작일</dt><dd>{date(round.starts_at)}</dd></div><div><dt>종료일</dt><dd>{date(round.ends_at)}</dd></div></dl><ParticipantRows data={data} round={round} states={states}/></article>}
function ParticipantRows({data,round,states}:{data:SurveyRecordData;round:SurveyRoundSummary;states:Map<string,RecordSubmission>}){return <div className="participant-table"><div className="participant-row participant-head"><span>이용인</span><span>상태</span><span>제출 일시</span><span>최종 수정</span><span>응답</span></div>{data.participants.map(person=>{const submission=states.get(person.id);const label=submission?.status==='submitted'?'완료':submission?.status==='draft'?'진행 중':'미완료';return <div className="participant-row" key={person.id}><span className="participant-name"><span className="mini-avatar">{person.photo_path?<img src={photoUrl(person.photo_path)} alt={`${person.name} 사진`}/>:person.name.slice(0,1)}</span><strong>{person.name}</strong></span><span data-label="상태"><StatusBadge tone={submission?.status==='submitted'?'success':submission?.status==='draft'?'warning':'neutral'}>{label}</StatusBadge></span><span data-label="제출 일시">{date(submission?.submitted_at??null,true)}</span><span data-label="최종 수정">{date(submission?.last_edited_at??null,true)}</span><span data-label="응답">{submission?.status==='submitted'&&<Link className="button secondary" to={`/surveys/run/${data.project.id}/${round.id}/${person.id}`}>응답 보기</Link>}</span></div>})}</div>}

function ResponsesTab({data}:{data:SurveyRecordData}){const [name,setName]=useState('');const [roundType,setRoundType]=useState('all');const [state,setState]=useState('all');const clients=new Map(data.participants.map(c=>[c.id,c]));const rounds=new Map(data.rounds.map(r=>[r.id,r]));const rows=data.submissions.filter(s=>(state==='all'||s.status===state)&&(roundType==='all'||rounds.get(s.survey_round_id)?.round_type===roundType)&&(clients.get(s.client_id)?.name??'').includes(name));return <><section className="completion-filters panel"><label>이용인 이름<input value={name} onChange={e=>setName(e.target.value)} placeholder="이름 검색"/></label><label>회차<select value={roundType} onChange={e=>setRoundType(e.target.value)}><option value="all">전체 회차</option><option value="single">단회</option><option value="pre">사전</option><option value="post">사후</option></select></label><label>완료 여부<select value={state} onChange={e=>setState(e.target.value)}><option value="all">전체</option><option value="submitted">완료</option><option value="draft">진행 중</option></select></label></section>{rows.length?<div className="participant-table response-records"><div className="participant-row participant-head"><span>이용인</span><span>회차</span><span>제출 일시</span><span>최종 수정</span><span>응답</span></div>{rows.map(s=>{const client=clients.get(s.client_id);const round=rounds.get(s.survey_round_id);return <div className="participant-row" key={s.id}><span><strong>{client?.name??'알 수 없음'}</strong></span><span data-label="회차">{round?roundLabels[round.round_type]:'—'} · {s.status==='submitted'?'완료':'진행 중'}</span><span data-label="제출 일시">{date(s.submitted_at,true)}</span><span data-label="최종 수정">{date(s.last_edited_at,true)}</span><span data-label="응답">{s.status==='submitted'&&round&&<><Link className="button secondary" to={`/surveys/run/${data.project.id}/${round.id}/${s.client_id}`}>응답 보기</Link> <Link className="button secondary" to={`/reports/${data.project.id}/print?roundId=${round.id}&clientId=${s.client_id}`}>개인 보고서</Link></>}</span></div>})}</div>:<EmptyState title="조건에 맞는 응답 기록이 없습니다." description="필터를 변경해 주세요."/>}</>}

const numericTypes=new Set(['face_3','face_5','scale_3','scale_5'])
function AnalysisTab({data,initialRoundId}:{data:SurveyRecordData;initialRoundId:string|null}){const available=data.rounds.filter(r=>r.status!=='pending');const initial=available.find(r=>r.id===initialRoundId)??available[0];const [view,setView]=useState<'single'|'pre'|'post'|'compare'>(initial?.round_type??'single');const selected=available.find(r=>r.round_type===view);if(!available.length)return <EmptyState title="분석할 회차가 없습니다." description="조사를 시작한 뒤 결과를 확인할 수 있습니다."/>;if(data.project.survey_type==='pre_post')return <><div className="tabs analysis-switch"><button className={view==='pre'?'active':''} onClick={()=>setView('pre')}>사전</button><button className={view==='post'?'active':''} onClick={()=>setView('post')} disabled={!available.some(r=>r.round_type==='post')}>사후</button><button className={view==='compare'?'active':''} onClick={()=>setView('compare')} disabled={!available.some(r=>r.round_type==='post')}>비교</button></div>{view==='compare'?<Comparison data={data}/>:selected?<RoundAnalysis data={data} round={selected}/>:<EmptyState title="사후 조사 완료 후 비교할 수 있습니다." description="사전 결과는 사전 탭에서 확인할 수 있습니다."/>}</>;return selected?<RoundAnalysis data={data} round={selected}/>:null}
function answersFor(data:SurveyRecordData,roundId:string){const ids=new Set(data.submissions.filter(s=>s.survey_round_id===roundId&&s.status==='submitted').map(s=>s.id));return data.answers.filter(a=>ids.has(a.survey_submission_id))}
function RoundAnalysis({data,round}:{data:SurveyRecordData;round:SurveyRoundSummary}){const submissions=data.submissions.filter(s=>s.survey_round_id===round.id&&s.status==='submitted');const answers=answersFor(data,round.id);const domains=[...new Set(data.questions.flatMap(q=>q.domain?[q.domain]:[]))];return <><section className="panel analysis-summary"><h2>{roundLabels[round.round_type]} 결과</h2><dl className="round-metrics"><div><dt>제출 완료</dt><dd>{submissions.length}명</dd></div><div><dt>미완료</dt><dd>{Math.max(0,data.participants.length-submissions.length)}명</dd></div><div><dt>완료율</dt><dd>{percent(submissions.length,data.participants.length)}%</dd></div></dl></section>{domains.length>0&&<DomainSummary questions={data.questions} answers={answers}/>}<div className="analysis-list">{data.questions.map((q,index)=><QuestionAnalysis key={q.id} question={q} answers={answers.filter(a=>a.survey_question_id===q.id)} total={submissions.length} index={index}/>)}</div></>}
function DomainSummary({questions,answers}:{questions:RecordQuestion[];answers:RecordAnswer[]}){const domains=[...new Set(questions.flatMap(q=>q.domain?[q.domain]:[]))];return <section className="panel"><h2>영역별 평균</h2><div className="domain-grid">{domains.map(domain=>{const ids=new Set(questions.filter(q=>q.domain===domain&&numericTypes.has(q.response_type)).map(q=>q.id));const values=answers.filter(a=>ids.has(a.survey_question_id)&&a.numeric_value!==null).map(a=>a.numeric_value!);return values.length?<div key={domain}><strong>{domain}</strong><span>{(values.reduce((a,b)=>a+b,0)/values.length).toFixed(2)}점</span></div>:null})}</div></section>}
function QuestionAnalysis({question,answers,total,index}:{question:RecordQuestion;answers:RecordAnswer[];total:number;index:number}){const present=answers.filter(a=>a.numeric_value!==null||Boolean(a.text_value?.trim()||a.staff_note?.trim())||a.option_ids.length);const countNumeric=(value:number)=>answers.filter(a=>a.numeric_value===value).length;let rows:{label:string;count:number;denominator?:number}[]=[];if(question.response_type==='face_3')rows=[{label:'네',count:countNumeric(3)},{label:'몰라요',count:countNumeric(2)},{label:'싫어요',count:countNumeric(1)},{label:'무응답',count:Math.max(0,total-present.length)}];else if(question.response_type==='face_5'||question.response_type==='scale_5')rows=[1,2,3,4,5].map(v=>({label:`${v}점`,count:countNumeric(v)}));else if(question.response_type==='scale_3')rows=[1,2,3].map(v=>({label:`${v}점`,count:countNumeric(v)}));else if(question.response_type==='yes_no'||question.response_type==='single_choice'||question.response_type==='multiple_choice'){rows=question.options.map(o=>({label:o.label,count:answers.filter(a=>a.option_ids.includes(o.id)).length,denominator:question.response_type==='multiple_choice'?present.length:total}));if(question.response_type==='yes_no')rows.push({label:'무응답',count:Math.max(0,total-present.length)})}const numeric=answers.filter(a=>a.numeric_value!==null).map(a=>a.numeric_value!);const texts=answers.map(a=>(a.staff_note??a.text_value)?.trim()).filter((v):v is string=>Boolean(v));return <article className="panel analysis-question">{question.domain&&<span className="domain-label">{question.domain}</span>}<h3>{index+1}. {question.question_text}</h3>{question.response_type==='staff_note'?<><p>{texts.length}건 응답 · 응답 없음 {Math.max(0,total-texts.length)}명</p>{texts.length?<ul className="text-responses">{texts.map((text,i)=><li key={i}>{text}</li>)}</ul>:<p className="muted">입력된 자유응답이 없습니다.</p>}</>:<><div className="distribution">{rows.map(row=>{const denominator=row.denominator??total;const rate=percent(row.count,denominator);return <div key={row.label}><span>{row.label}</span><div className="bar-track"><i style={{width:`${rate}%`}}/></div><strong>{row.count}명 / {rate}%</strong></div>})}</div>{numeric.length>0&&numericTypes.has(question.response_type)&&<p className="analysis-average">응답자 {numeric.length}명 · 평균 {(numeric.reduce((a,b)=>a+b,0)/numeric.length).toFixed(2)}점</p>}{question.response_type==='multiple_choice'&&<p className="notice">복수응답 문항은 비율 합계가 100%를 초과할 수 있습니다.</p>}</>}</article>}

function Comparison({data}:{data:SurveyRecordData}){const pre=data.rounds.find(r=>r.round_type==='pre');const post=data.rounds.find(r=>r.round_type==='post');if(!pre||!post)return <EmptyState title="사후 조사 완료 후 비교할 수 있습니다." description="사전 결과는 정상적으로 확인할 수 있습니다."/>;const preSubs=data.submissions.filter(s=>s.survey_round_id===pre.id&&s.status==='submitted');const postSubs=data.submissions.filter(s=>s.survey_round_id===post.id&&s.status==='submitted');const preByClient=new Map(preSubs.map(s=>[s.client_id,s]));const postByClient=new Map(postSubs.map(s=>[s.client_id,s]));const paired=[...preByClient.keys()].filter(id=>postByClient.has(id));const answerMap=new Map(data.answers.map(a=>[`${a.survey_submission_id}:${a.survey_question_id}`,a]));return <><section className="panel"><h2>동일 이용인 paired 비교</h2><dl className="round-metrics"><div><dt>사전 완료</dt><dd>{preSubs.length}명</dd></div><div><dt>사후 완료</dt><dd>{postSubs.length}명</dd></div><div><dt>비교 가능</dt><dd>{paired.length}명</dd></div></dl><p className="muted">사전과 사후를 모두 제출한 동일 이용인만 변화량에 포함합니다.</p></section><div className="analysis-list">{data.questions.map((q,index)=>numericTypes.has(q.response_type)?<NumericComparison key={q.id} question={q} index={index} clients={paired} pre={preByClient} post={postByClient} answers={answerMap}/>:<ChoiceComparison key={q.id} question={q} index={index} preAnswers={answersFor(data,pre.id)} postAnswers={answersFor(data,post.id)} preTotal={preSubs.length} postTotal={postSubs.length}/>)}</div></>}
function NumericComparison({question,index,clients,pre,post,answers}:{question:RecordQuestion;index:number;clients:string[];pre:Map<string,RecordSubmission>;post:Map<string,RecordSubmission>;answers:Map<string,RecordAnswer>}){const pairs=clients.flatMap(id=>{const a=answers.get(`${pre.get(id)!.id}:${question.id}`)?.numeric_value;const b=answers.get(`${post.get(id)!.id}:${question.id}`)?.numeric_value;return a!==null&&a!==undefined&&b!==null&&b!==undefined?[[a,b] as [number,number]]:[]});const preAvg=pairs.length?pairs.reduce((s,p)=>s+p[0],0)/pairs.length:0;const postAvg=pairs.length?pairs.reduce((s,p)=>s+p[1],0)/pairs.length:0;return <article className="panel analysis-question">{question.domain&&<span className="domain-label">{question.domain}</span>}<h3>{index+1}. {question.question_text}</h3>{pairs.length?<dl className="comparison-grid"><div><dt>사전 평균</dt><dd>{preAvg.toFixed(2)}</dd></div><div><dt>사후 평균</dt><dd>{postAvg.toFixed(2)}</dd></div><div><dt>변화량</dt><dd>{(postAvg-preAvg).toFixed(2)}</dd></div><div><dt>증가</dt><dd>{pairs.filter(p=>p[1]>p[0]).length}명</dd></div><div><dt>동일</dt><dd>{pairs.filter(p=>p[1]===p[0]).length}명</dd></div><div><dt>감소</dt><dd>{pairs.filter(p=>p[1]<p[0]).length}명</dd></div><div><dt>비교 대상</dt><dd>{pairs.length}명</dd></div></dl>:<p className="muted">비교 가능한 수치 응답이 없습니다.</p>}</article>}
function ChoiceComparison({question,index,preAnswers,postAnswers,preTotal,postTotal}:{question:RecordQuestion;index:number;preAnswers:RecordAnswer[];postAnswers:RecordAnswer[];preTotal:number;postTotal:number}){if(question.response_type==='staff_note')return <QuestionAnalysis question={question} answers={postAnswers.filter(a=>a.survey_question_id===question.id)} total={postTotal} index={index}/>;const options=question.options;return <article className="panel analysis-question">{question.domain&&<span className="domain-label">{question.domain}</span>}<h3>{index+1}. {question.question_text}</h3><div className="choice-comparison">{options.map(o=>{const before=preAnswers.filter(a=>a.survey_question_id===question.id&&a.option_ids.includes(o.id)).length;const after=postAnswers.filter(a=>a.survey_question_id===question.id&&a.option_ids.includes(o.id)).length;return <div key={o.id}><strong>{o.label}</strong><span>사전 {before}명 / {percent(before,preTotal)}%</span><span>사후 {after}명 / {percent(after,postTotal)}%</span></div>})}</div>{question.response_type==='multiple_choice'&&<p className="notice">복수응답 문항은 비율 합계가 100%를 초과할 수 있습니다.</p>}</article>}
function ReportTab({data}:{data:SurveyRecordData}){const [roundId,setRoundId]=useState(data.rounds.find(r=>r.status!=='pending')?.id??'');const [clientId,setClientId]=useState('');const query=`?roundId=${roundId}${clientId?`&clientId=${clientId}`:''}`;return <section className="panel report-options"><h2>인쇄 / PDF 저장</h2><p>회차와 필요 시 이용인을 선택한 뒤 기존 인쇄 화면에서 브라우저의 PDF 저장 기능을 사용하세요.</p><label>회차<select value={roundId} onChange={e=>setRoundId(e.target.value)}>{data.rounds.filter(r=>r.status!=='pending').map(r=><option value={r.id} key={r.id}>{roundLabels[r.round_type]}</option>)}</select></label><label>이용인<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">전체 이용인</option>{data.participants.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><Link className="button primary" to={`/reports/${data.project.id}/print${query}`}>보고서 열기</Link></section>}
