import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ErrorState, LoadingState, PageHeader, StatusBadge } from '../components/ui'
import { useAuth } from '../context/AuthContext'
import { defaultSurveyTemplates } from '../data/defaultSurveyTemplates'
import { loadSharedData, loadSurvey, saveSurvey } from '../lib/surveys'
import type { QuestionDraft, ResponseType, SharedClient, SharedProgram, SurveyDraft } from '../types/survey'

const responseLabels: Record<ResponseType,string> = { face_3:'3점 표정', face_5:'5점 표정', scale_3:'3점 척도', scale_5:'5점 척도', yes_no:'예·아니오', single_choice:'단일 선택', multiple_choice:'복수 선택', staff_note:'직원 메모' }
const blankQuestion = (): QuestionDraft => ({ id:crypto.randomUUID(), domain:'', question_text:'', response_type:'face_5', is_required:true, options:[] })
const emptyDraft: SurveyDraft = { title:'', description:'', survey_type:'single', program_id:'', template_key:'blank-single', participant_ids:[], questions:[] }

export function SurveyEditor() {
  const { surveyId } = useParams(); const { profile } = useAuth(); const navigate=useNavigate()
  const [step,setStep]=useState(1); const [draft,setDraft]=useState<SurveyDraft>(emptyDraft); const [clients,setClients]=useState<SharedClient[]>([]); const [programs,setPrograms]=useState<SharedProgram[]>([])
  const [loading,setLoading]=useState(true); const [savingAction,setSavingAction]=useState<'draft'|'scheduled'|'start'|null>(null); const [error,setError]=useState(''); const [sharedWarning,setSharedWarning]=useState(''); const [search,setSearch]=useState(''); const [readOnly,setReadOnly]=useState(false)
  const savingRef=useRef(false); const saving=savingAction!==null
  useEffect(()=>{ if(!profile)return; let active=true; (async()=>{ try { const shared=await loadSharedData(profile.organization_id); if(!active)return; setClients(shared.clients); setPrograms(shared.programs); if(shared.clientsError||shared.programsError)setSharedWarning('공유 이용인 또는 프로그램 정보를 불러오지 못했습니다. 테이블 구조를 확인해 주세요.'); if(surveyId){ const loaded=await loadSurvey(surveyId,profile.organization_id); setDraft(loaded.draft); setReadOnly(loaded.project.status!=='draft') } } catch(e){setError(e instanceof Error?e.message:'정보를 불러오지 못했습니다.')} finally{setLoading(false)} })(); return()=>{active=false} },[profile,surveyId])
  const updateQuestion=(id:string,patch:Partial<QuestionDraft>)=>setDraft(d=>({...d,questions:d.questions.map(q=>q.id===id?{...q,...patch}:q)}))
  const filtered=useMemo(()=>clients.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())),[clients,search])
  const validate=(target:number)=>{ if(target>1&&!draft.title.trim())return '조사 제목을 입력해 주세요.'; if(target>2){if(!draft.participant_ids.length)return '참여 이용인을 한 명 이상 선택해 주세요.'; if(!draft.questions.length)return '질문을 한 개 이상 추가해 주세요.'; for(const q of draft.questions){if(!q.question_text.trim())return '빈 질문 문구를 확인해 주세요.'; if((q.response_type==='single_choice'||q.response_type==='multiple_choice')&&(q.options.length<2||q.options.some(o=>!o.label.trim())))return '선택형 질문에는 내용이 있는 선택지가 2개 이상 필요합니다.'}} return ''}
  const next=()=>{const message=validate(step+1);setError(message);if(!message)setStep(s=>Math.min(3,s+1))}
  const save=async(action:'draft'|'scheduled'|'start')=>{if(savingRef.current)return;const message=validate(3);if(message){setError(message);return} if(!profile)return;savingRef.current=true;setSavingAction(action);setError('');try{await saveSurvey(draft,profile.organization_id,action,surveyId);navigate('/surveys')}catch(e){setError(e instanceof Error?e.message:'저장하지 못했습니다.')}finally{savingRef.current=false;setSavingAction(null)}}
  if(loading)return <LoadingState label="조사 편집 정보를 불러오고 있습니다." />
  return <><PageHeader title={surveyId?'조사 수정':'새 조사'} description={readOnly?'확정되었거나 시작한 조사는 기록 보호를 위해 읽기 전용입니다.':'3단계로 조사 내용과 참여자를 안전하게 구성합니다.'}/>
    <ol className="wizard-steps">{['기본 정보','참여자 · 질문','확인 · 저장'].map((label,i)=><li className={step===i+1?'active':''} key={label}><span>{i+1}</span>{label}</li>)}</ol>
    {error&&<ErrorState message={error}/>} {sharedWarning&&<p className="notice">{sharedWarning}</p>}
    <fieldset disabled={readOnly||saving} className="editor-fieldset">
    {step===1&&<div className="editor-stack"><section className="panel"><h2>기본 프리셋</h2><div className="template-grid">{defaultSurveyTemplates.map(t=><button type="button" className={`template-card ${draft.template_key===t.key?'selected':''}`} key={t.key} onClick={()=>setDraft(d=>({...d,title:t.title,survey_type:t.survey_type,template_key:t.key,questions:t.questions.map(q=>({...q,id:crypto.randomUUID(),options:q.options.map(o=>({...o,id:crypto.randomUUID()}))}))}))}><strong>{t.name}</strong><span>{t.description}</span></button>)}</div></section>
      <section className="panel form-grid"><label>조사 제목<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>조사 유형<select value={draft.survey_type} onChange={e=>setDraft({...draft,survey_type:e.target.value as SurveyDraft['survey_type']})}><option value="single">단회 조사</option><option value="pre_post">사전·사후 비교조사</option></select></label><label className="wide">설명 (선택)<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>프로그램 (선택)<select value={draft.program_id} onChange={e=>setDraft({...draft,program_id:e.target.value})}><option value="">선택 안 함</option>{programs.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label></section></div>}
    {step===2&&<div className="editor-stack"><section className="panel"><div className="section-heading"><div><h2>참여자 선택</h2><p>{draft.participant_ids.length}명 선택</p></div><div className="compact-actions"><button type="button" className="button secondary" onClick={()=>setDraft({...draft,participant_ids:filtered.map(c=>c.id)})}>전체 선택</button><button type="button" className="button secondary" onClick={()=>setDraft({...draft,participant_ids:[]})}>전체 해제</button></div></div><input aria-label="이용인 이름 검색" placeholder="이름 검색" value={search} onChange={e=>setSearch(e.target.value)}/><div className="client-grid">{filtered.map(c=><label className={`client-card ${draft.participant_ids.includes(c.id)?'selected':''}`} key={c.id}><input type="checkbox" checked={draft.participant_ids.includes(c.id)} onChange={()=>setDraft(d=>({...d,participant_ids:d.participant_ids.includes(c.id)?d.participant_ids.filter(id=>id!==c.id):[...d.participant_ids,c.id]}))}/><span className="avatar">{c.name.slice(0,1)}</span><strong>{c.name}</strong></label>)}</div>{!clients.length&&<p className="muted">표시할 활성 이용인이 없습니다.</p>}</section>
      <section className="panel"><div className="section-heading"><div><h2>질문 구성</h2><p>{draft.questions.length}개 문항</p></div><button type="button" className="button primary" onClick={()=>setDraft(d=>({...d,questions:[...d.questions,blankQuestion()]}))}>질문 추가</button></div><div className="question-list">{draft.questions.map((q,index)=><article className="question-card" key={q.id}><div className="question-number">문항 {index+1}</div><div className="form-grid"><label>응답 방식<select value={q.response_type} onChange={e=>updateQuestion(q.id,{response_type:e.target.value as ResponseType,options:['single_choice','multiple_choice'].includes(e.target.value)&&q.options.length<2?[{id:crypto.randomUUID(),label:''},{id:crypto.randomUUID(),label:''}]:q.options})}>{Object.entries(responseLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="wide">질문 문구<textarea value={q.question_text} onChange={e=>updateQuestion(q.id,{question_text:e.target.value})}/></label></div><details className="question-domain" open={q.domain.trim().length>0||undefined}><summary>{q.domain.trim()?`영역/분류: ${q.domain}`:'영역/분류 추가 (선택)'}</summary><label>영역/분류 (선택)<input value={q.domain} onChange={e=>updateQuestion(q.id,{domain:e.target.value})}/></label></details>{['single_choice','multiple_choice'].includes(q.response_type)&&<div className="options"><strong>선택지</strong>{q.options.map((o,oi)=><div className="option-row" key={o.id}><input aria-label={`선택지 ${oi+1}`} value={o.label} onChange={e=>updateQuestion(q.id,{options:q.options.map(x=>x.id===o.id?{...x,label:e.target.value}:x)})}/><button type="button" onClick={()=>updateQuestion(q.id,{options:q.options.filter(x=>x.id!==o.id)})}>삭제</button></div>)}<button type="button" className="button secondary" onClick={()=>updateQuestion(q.id,{options:[...q.options,{id:crypto.randomUUID(),label:''}]})}>선택지 추가</button></div>}<div className="question-actions"><label><input type="checkbox" checked={q.is_required} onChange={e=>updateQuestion(q.id,{is_required:e.target.checked})}/> 필수 응답</label><button type="button" disabled={!index} onClick={()=>setDraft(d=>({...d,questions:d.questions.map((x,i)=>i===index-1?q:i===index?d.questions[index-1]:x)}))}>위로</button><button type="button" disabled={index===draft.questions.length-1} onClick={()=>setDraft(d=>({...d,questions:d.questions.map((x,i)=>i===index+1?q:i===index?d.questions[index+1]:x)}))}>아래로</button><button type="button" onClick={()=>setDraft(d=>({...d,questions:[...d.questions.slice(0,index+1),{...q,id:crypto.randomUUID(),options:q.options.map(o=>({...o,id:crypto.randomUUID()}))},...d.questions.slice(index+1)]}))}>복제</button><button type="button" className="danger-text" onClick={()=>setDraft(d=>({...d,questions:d.questions.filter(x=>x.id!==q.id)}))}>삭제</button></div></article>)}</div></section></div>}
    {step===3&&<section className="panel review"><h2>조사 내용 확인</h2><dl><dt>제목</dt><dd>{draft.title}</dd><dt>유형</dt><dd>{draft.survey_type==='single'?'단회 조사':'사전·사후 비교조사'}</dd><dt>프로그램</dt><dd>{programs.find(p=>p.id===draft.program_id)?.name??'선택 안 함'}</dd><dt>참여자</dt><dd>{clients.filter(c=>draft.participant_ids.includes(c.id)).map(c=>c.name).join(', ')} ({draft.participant_ids.length}명)</dd><dt>프리셋</dt><dd>{defaultSurveyTemplates.find(t=>t.key===draft.template_key)?.name??'없음'}</dd></dl><h3>질문 {draft.questions.length}개</h3><ol>{draft.questions.map(q=><li key={q.id}><strong>{q.domain&&`[${q.domain}] `}{q.question_text}</strong> <StatusBadge>{responseLabels[q.response_type]}</StatusBadge></li>)}</ol>{draft.survey_type==='pre_post'&&<p className="notice">사전 회차를 먼저 시작하고 사후 회차는 대기 상태로 저장합니다. 두 회차는 같은 질문을 공유합니다.</p>}</section>}
    </fieldset><div className="wizard-actions">{step>1&&<button className="button secondary" onClick={()=>setStep(s=>s-1)} disabled={saving}>이전</button>}<span/>{step<3?<button className="button primary" onClick={next}>다음</button>:!readOnly&&<><button className="button secondary" disabled={saving} onClick={()=>void save('draft')}>{savingAction==='draft'?'임시저장 중…':'임시저장'}</button><button className="button secondary" disabled={saving} onClick={()=>void save('scheduled')}>{savingAction==='scheduled'?'예정 등록 중…':'예정으로 등록'}</button><button className="button primary" disabled={saving} onClick={()=>void save('start')}>{savingAction==='start'?'조사 시작 중…':'조사 시작'}</button></>}</div></>
}
