import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ConfirmDialog, EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from '../components/ui'
import { useAuth } from '../context/AuthContext'
import { getSupabase } from '../lib/supabase'
import { listRunnableSurveys, loadRunParticipants, loadRunQuestions, loadSavedAnswers, saveRunAnswer, startRun, submitRun } from '../lib/surveys'
import type { RunParticipant, RunQuestion, RunSurvey, SavedAnswer, SurveyRoundType } from '../types/survey'

const roundLabel:Record<SurveyRoundType,string>={single:'단회',pre:'사전',post:'사후'}
const faces=['😣','🙁','😐','🙂','😄']; const faceLabels=['매우 어려워요','어려워요','보통이에요','좋아요','매우 좋아요']
const photoUrl=(path:string|null)=>{if(!path)return null;if(/^https?:\/\//.test(path))return path;return getSupabase()?.storage.from('client-photos').getPublicUrl(path).data.publicUrl??null}
function Avatar({client,large=false}:{client:Pick<RunParticipant,'name'|'photo_path'>;large?:boolean}){const [failed,setFailed]=useState(false);const src=photoUrl(client.photo_path);return <span className={`run-avatar ${large?'large':''}`}>{src&&!failed?<img src={src} alt={`${client.name} 사진`} onError={()=>setFailed(true)}/>:<span aria-hidden="true">{client.name.slice(0,1)}</span>}</span>}

export function SurveyRunPage(){
  const {profile}=useAuth();const navigate=useNavigate();const {surveyId,roundId,clientId}=useParams();
  const targetKey=`${surveyId??''}:${roundId??''}:${clientId??''}`;const targetRef=useRef(targetKey);targetRef.current=targetKey
  const [surveys,setSurveys]=useState<RunSurvey[]>([]);const [participants,setParticipants]=useState<RunParticipant[]>([]);const [questions,setQuestions]=useState<RunQuestion[]>([]);const [answers,setAnswers]=useState<Record<string,SavedAnswer>>({});
  const [submissionId,setSubmissionId]=useState('');const [index,setIndex]=useState(0);const [review,setReview]=useState(false);const [confirm,setConfirm]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [saved,setSaved]=useState('');const [error,setError]=useState('');const [search,setSearch]=useState('');const [filter,setFilter]=useState<'all'|'incomplete'|'submitted'>('all');
  const survey=surveys.find(s=>s.id===surveyId);const round=survey?.rounds.find(r=>r.id===roundId);const participant=participants.find(p=>p.id===clientId)
  const refreshSurveys=()=>profile?listRunnableSurveys(profile.organization_id).then(setSurveys):Promise.resolve()
  useEffect(()=>{setError('');setSubmissionId('');setQuestions([]);setAnswers({});setIndex(0);setSaved('');setReview(false);setConfirm(false);setSaving(false);setLoading(Boolean(surveyId))},[targetKey,surveyId])
  useEffect(()=>{if(!profile)return;let active=true;setLoading(true);refreshSurveys().catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[profile])
  useEffect(()=>{if(!profile||!surveyId||!roundId)return;let active=true;setLoading(true);loadRunParticipants(surveyId,roundId,profile.organization_id).then(data=>{if(active)setParticipants(data)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[profile,surveyId,roundId])
  useEffect(()=>{if(!surveyId||!roundId||!clientId)return;let active=true;const requestTarget=targetKey;setError('');setLoading(true);(async()=>{try{const started=await startRun(roundId,clientId);if(!active||targetRef.current!==requestTarget)return;setError('');if(started.already_completed){setError('이미 완료된 조사입니다.');return}const [qs,savedAnswers]=await Promise.all([loadRunQuestions(surveyId),loadSavedAnswers(started.submission_id)]);if(!active||targetRef.current!==requestTarget)return;setError('');setSubmissionId(started.submission_id);setQuestions(qs);setAnswers(Object.fromEntries(savedAnswers.map(a=>[a.question_id,a])))}catch(e){if(active&&targetRef.current===requestTarget)setError(e instanceof Error?e.message:'조사를 시작하지 못했습니다.')}finally{if(active&&targetRef.current===requestTarget)setLoading(false)}})();return()=>{active=false}},[surveyId,roundId,clientId,targetKey])
  const shown=useMemo(()=>participants.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||(filter==='submitted'?p.submission_status==='submitted':p.submission_status!=='submitted'))),[participants,search,filter]);
  const valid=(q:RunQuestion,a?:SavedAnswer)=>!q.is_required||Boolean(a&&(q.response_type==='staff_note'?a.text_value?.trim():q.response_type.includes('choice')||q.response_type==='yes_no'?a.option_ids.length:a.numeric_value));
  const save=async(q:RunQuestion,a:SavedAnswer)=>{const requestTarget=targetKey;const requestSubmission=submissionId;setSaving(true);setSaved('');try{await saveRunAnswer(requestSubmission,a);if(targetRef.current===requestTarget){setError('');setSaved('저장됨')}}catch(e){if(targetRef.current===requestTarget)setError(e instanceof Error?e.message:'응답을 저장하지 못했습니다.');throw e}finally{if(targetRef.current===requestTarget)setSaving(false)}}
  const choose=async(a:SavedAnswer)=>{setAnswers(old=>({...old,[a.question_id]:a}));try{await save(questions[index],a)}catch{/* Keep the local answer visible for retry. */}}
  const next=async()=>{const q=questions[index],a=answers[q.id];if(!valid(q,a)){setError('필수 문항에 응답한 뒤 다음으로 이동해 주세요.');return}setError('');if(a)try{await save(q,a)}catch{return}if(index===questions.length-1)setReview(true);else setIndex(i=>i+1)}
  const finish=async()=>{const requestTarget=targetKey;const requestSubmission=submissionId;setSaving(true);try{await submitRun(requestSubmission);if(targetRef.current!==requestTarget)return;setError('');setConfirm(false);navigate(`/surveys/run/${surveyId}/${roundId}`,{state:{completedClientId:clientId}})}catch(e){if(targetRef.current===requestTarget)setError(e instanceof Error?e.message:'제출하지 못했습니다.')}finally{if(targetRef.current===requestTarget)setSaving(false)}}
  if(loading)return <LoadingState label="조사 진행 정보를 불러오고 있습니다."/>
  if(!surveyId)return <><PageHeader title="조사 진행" description="현재 열린 회차를 선택해 만족도 조사를 진행합니다."/>{error&&<ErrorState message={error}/>}<div className="filters"><input aria-label="진행 조사 검색" placeholder="조사 제목 또는 프로그램 검색" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="회차 유형" value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="all">모든 회차</option><option value="incomplete">단회 / 사전</option><option value="submitted">사후</option></select></div>{surveys.length?<div className="survey-grid">{surveys.filter(s=>`${s.title} ${s.program_name??''}`.toLowerCase().includes(search.toLowerCase())).map(s=>{const open=s.rounds.filter(r=>r.status==='open');const bad=open.length!==1;const r=open[0];return <article className="survey-card" key={s.id}><StatusBadge tone={bad?'warning':'success'}>{bad?'회차 상태 확인 필요':`${roundLabel[r.round_type]} 진행 중`}</StatusBadge><h2>{s.title}</h2><p>{s.program_name??'프로그램 미지정'} · {s.survey_type==='single'?'단회':'사전·사후'}</p><p>전체 {s.participant_count}명 · 완료 {s.completed_count}명 · 미완료 {Math.max(0,s.participant_count-s.completed_count)}명</p><p>시작일 {s.starts_at?new Date(s.starts_at).toLocaleDateString('ko-KR'):'미지정'}</p><Link aria-disabled={bad} className={`button primary ${bad?'disabled':''}`} to={bad?'#':`/surveys/run/${s.id}/${r.id}`}>{bad?'진행 불가':`${roundLabel[r.round_type]} 조사 진행`}</Link></article>})}</div>:<EmptyState title="진행할 조사가 없습니다." description="열린 조사와 회차가 있는지 확인해 주세요."/>}</>
  if(!clientId){const completed=participants.filter(p=>p.submission_status==='submitted').length;return <><PageHeader title={survey?.title??'참여 이용인'} description={`${round?roundLabel[round.round_type]:''} 회차 · 완료 ${completed}명 · 미완료 ${participants.length-completed}명`} action={<Link className="button secondary" to="/surveys/run">조사 목록</Link>}/>{error&&<ErrorState message={error}/>}<div className="filters"><input aria-label="이용인 이름 검색" placeholder="이용인 이름 검색" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="완료 상태" value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="all">모든 상태</option><option value="incomplete">미완료·진행 중</option><option value="submitted">완료</option></select></div><div className="run-client-grid">{shown.map(p=><article className="run-client-card" key={p.id}><Avatar client={p} large/><h2>{p.name}</h2><StatusBadge tone={p.submission_status==='submitted'?'success':p.submission_status==='draft'?'warning':'neutral'}>{p.submission_status==='submitted'?'완료':p.submission_status==='draft'?'진행 중':'미완료'}</StatusBadge>{p.submission_status==='submitted'?<button className="button secondary" onClick={()=>setError('이미 완료된 조사입니다.')}>완료됨</button>:<Link className="button primary" to={`/surveys/run/${surveyId}/${roundId}/${p.id}`}>{p.submission_status==='draft'?'이어하기':'조사 시작'}</Link>}</article>)}</div>{!shown.length&&<EmptyState title="조건에 맞는 이용인이 없습니다." description="검색어나 완료 상태 필터를 변경해 주세요."/>}</>}
  if(error&&!submissionId)return <><ErrorState message={error}/><Link className="button secondary" to={`/surveys/run/${surveyId}/${roundId}`}>이용인 목록</Link></>
  if(!participant||!round||!questions.length)return <ErrorState message="조사 문항 또는 이용인 정보를 확인할 수 없습니다."/>
  if(review){const missing=questions.filter(q=>!valid(q,answers[q.id]));return <><PageHeader title="응답 확인" description={`${participant.name} · ${survey?.title} · ${roundLabel[round.round_type]} 회차`}/>{error&&<ErrorState message={error}/>}<section className="run-review panel"><div className="run-person"><Avatar client={participant}/><strong>{participant.name}</strong></div><p>응답한 문항 {questions.length-missing.length} / {questions.length}</p>{missing.length>0&&<p className="notice">누락된 필수 문항: {missing.map(q=>q.sort_order).join(', ')}번</p>}<ol>{questions.map((q,i)=><li key={q.id}><button onClick={()=>{setIndex(i);setReview(false)}}><strong>{i+1}. {q.question_text}</strong><span>{summary(q,answers[q.id])}</span></button></li>)}</ol><div className="run-footer"><button className="button secondary" onClick={()=>setReview(false)}>응답 수정</button><button className="button primary" disabled={missing.length>0||saving} onClick={()=>setConfirm(true)}>최종 제출</button></div></section><ConfirmDialog open={confirm} title="응답을 최종 제출할까요?" description="제출 후에는 이번 화면에서 수정할 수 없습니다." confirmLabel="최종 제출" onClose={()=>setConfirm(false)} onConfirm={()=>void finish()}/></>}
  const q=questions[index],a=answers[q.id];return <div className="run-page"><header className="run-header"><div className="run-person"><Avatar client={participant}/><div><strong>{participant.name}</strong><span>{survey?.title} · {roundLabel[round.round_type]}</span></div></div><div className="run-progress"><span>{index+1} / {questions.length}</span><progress value={index+1} max={questions.length}/></div></header>{error&&<ErrorState message={error}/>}<section className="run-question"><p>{q.domain||'만족도 문항'} · {q.is_required?'필수':'선택'}</p><h1>{q.question_text}</h1><AnswerInput question={q} answer={a} disabled={saving} onChange={choose}/></section><footer className="run-footer"><button className="button secondary" disabled={index===0||saving} onClick={()=>{setError('');setIndex(i=>i-1)}}>이전</button><span aria-live="polite">{saving?'저장 중…':saved||'응답을 선택하면 저장됩니다.'}</span><button className="button primary" disabled={saving} onClick={()=>void next()}>{index===questions.length-1?'응답 확인':'다음'}</button></footer></div>
}

function AnswerInput({question:q,answer,disabled,onChange}:{question:RunQuestion;answer?:SavedAnswer;disabled:boolean;onChange:(a:SavedAnswer)=>void}){const base={question_id:q.id,numeric_value:null,text_value:null,option_ids:[]} satisfies SavedAnswer;if(q.response_type==='staff_note')return <label className="note-input"><textarea maxLength={2000} value={answer?.text_value??''} onChange={e=>onChange({...base,text_value:e.target.value})} disabled={disabled} placeholder="담당자 메모를 입력해 주세요."/><span>{answer?.text_value?.length??0} / 2,000자</span></label>;if(q.response_type.startsWith('face_')||q.response_type.startsWith('scale_')){const count=q.response_type.endsWith('3')?3:5;return <div className={`answer-grid ${q.response_type.startsWith('face_')?'faces':''}`}>{Array.from({length:count},(_,i)=>i+1).map((v,i)=><button disabled={disabled} aria-pressed={answer?.numeric_value===v} className={answer?.numeric_value===v?'selected':''} key={v} onClick={()=>onChange({...base,numeric_value:v})}><b>{q.response_type.startsWith('face_')?faces[count===3?[0,2,4][i]:i]:v}</b><span>{q.response_type.startsWith('face_')?(count===3?[faceLabels[0],faceLabels[2],faceLabels[4]][i]:faceLabels[i]):`${v}점`}</span></button>)}</div>}const options=q.response_type==='yes_no'&&q.options.length===0?[]:q.options;return options.length?<div className="choice-grid">{options.map(o=>{const selected=answer?.option_ids.includes(o.id)??false;return <button disabled={disabled} aria-pressed={selected} className={selected?'selected':''} key={o.id} onClick={()=>{const ids=q.response_type==='multiple_choice'?(selected?answer!.option_ids.filter(id=>id!==o.id):[...(answer?.option_ids??[]),o.id]):[o.id];onChange({...base,option_ids:ids})}}>{o.label}</button>})}</div>:<ErrorState message="이 문항에 등록된 선택지가 없습니다."/>}
function summary(q:RunQuestion,a?:SavedAnswer){if(!a)return '응답 없음';if(q.response_type==='staff_note')return a.text_value||'응답 없음';if(a.numeric_value)return `${a.numeric_value}점`;return a.option_ids.map(id=>q.options.find(o=>o.id===id)?.label).filter(Boolean).join(', ')||'응답 없음'}
